[2023-06-08T10:58:47.797995+00:00 INFO] [plan:196] ################################################################################
[2023-06-08T10:58:47.798150+00:00 INFO] [plan:197] Starting Reliably experiment: https://app.reliably.com/api/v1/organization/423320d0-f114-44d8-ba48-788577b2c4ac/experiments/1f9ee18a-9b03-4e44-b197-def008ec914e/raw
[2023-06-08T10:58:47.798368+00:00 DEBUG] [__init__:206] Loading global control 'reliably-integration-slack'
[2023-06-08T10:58:48.170545+00:00 DEBUG] [caching:24] Building activity cache...
[2023-06-08T10:58:48.170712+00:00 DEBUG] [caching:35] Cached 1 activities
[2023-06-08T10:58:48.171177+00:00 INFO] [experiment:58] Validating the experiment's syntax
[2023-06-08T10:58:48.171283+00:00 DEBUG] [configuration:63] Loading configuration...
[2023-06-08T10:58:48.171385+00:00 DEBUG] [secret:78] Loading secrets...
[2023-06-08T10:58:48.171570+00:00 DEBUG] [secret:103] Done loading secrets
[2023-06-08T10:58:48.218966+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'validate_control'
[2023-06-08T10:58:48.219071+00:00 INFO] [experiment:109] Experiment looks valid
[2023-06-08T10:58:48.219116+00:00 DEBUG] [caching:42] Clearing activities cache
[2023-06-08T10:58:48.219164+00:00 DEBUG] [caching:24] Building activity cache...
[2023-06-08T10:58:48.219202+00:00 DEBUG] [caching:35] Cached 1 activities
[2023-06-08T10:58:48.219299+00:00 DEBUG] [configuration:63] Loading configuration...
[2023-06-08T10:58:48.219375+00:00 DEBUG] [secret:78] Loading secrets...
[2023-06-08T10:58:48.219413+00:00 DEBUG] [secret:103] Done loading secrets
[2023-06-08T10:58:48.219452+00:00 DEBUG] [configuration:160] Loading dynamic configuration...
[2023-06-08T10:58:48.219541+00:00 INFO] [run:369] Running experiment: Certificate is always valid and has not expired
[2023-06-08T10:58:48.221425+00:00 DEBUG] [__init__:171] Initializing global control 'reliably-integration-slack'
[2023-06-08T10:58:48.221511+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosslack/control.py' does not declare 'configure_control'
[2023-06-08T10:58:48.221554+00:00 DEBUG] [__init__:64] Initializing controls
[2023-06-08T10:58:48.221593+00:00 DEBUG] [__init__:73] Initializing control 'reliably'
[2023-06-08T10:58:48.221640+00:00 DEBUG] [python:196] Control 'configure_control' loaded from '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py'
[2023-06-08T10:58:48.221731+00:00 DEBUG] [experiment:423] Configure Reliably's experiment control
[2023-06-08T10:58:48.221920+00:00 DEBUG] [experiment:587] Sending plan '55e8c598-fa50-46d6-aec7-7b8544afc971' status: running
[2023-06-08T10:58:48.994698+00:00 INFO] [experiment:202] Reliably execution: 91636fe5-ca1a-4342-ba7d-8b05e2077007
[2023-06-08T10:58:49.258798+00:00 DEBUG] [experiment:612] Sending execution state: {'current': 'running', 'started_on': '2023-06-08T10:58:48.221768+00:00', 'plan_id': '55e8c598-fa50-46d6-aec7-7b8544afc971'}
[2023-06-08T10:58:49.713164+00:00 DEBUG] [experiment:81] Starting Reliably state checker now
[2023-06-08T10:58:49.713297+00:00 INFO] [run:396] Steady-state strategy: default
[2023-06-08T10:58:49.714710+00:00 INFO] [run:400] Rollbacks strategy: always
[2023-06-08T10:58:49.715153+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'experiment'
[2023-06-08T10:58:49.715597+00:00 DEBUG] [python:196] Control 'before_experiment_control' loaded from '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py'
[2023-06-08T10:58:49.716160+00:00 DEBUG] [__init__:459] Applying before-control 'reliably-integration-slack' on 'experiment'
[2023-06-08T10:58:49.716628+00:00 DEBUG] [python:196] Control 'before_experiment_control' loaded from '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-06-08T10:58:49.858332+00:00 DEBUG] [run:558] Running steady-state hypothesis before the method
[2023-06-08T10:58:49.858757+00:00 INFO] [hypothesis:186] Steady state hypothesis: Capture certificate and perform the checks
[2023-06-08T10:58:49.859155+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'hypothesis'
[2023-06-08T10:58:49.859445+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_hypothesis_control'
[2023-06-08T10:58:49.859757+00:00 DEBUG] [__init__:459] Applying before-control 'reliably-integration-slack' on 'hypothesis'
[2023-06-08T10:58:49.860043+00:00 DEBUG] [python:196] Control 'before_hypothesis_control' loaded from '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-06-08T10:58:50.006150+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'activity'
[2023-06-08T10:58:50.006395+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-06-08T10:58:50.006461+00:00 DEBUG] [__init__:459] Applying before-control 'reliably-integration-slack' on 'activity'
[2023-06-08T10:58:50.006523+00:00 DEBUG] [python:196] Control 'before_activity_control' loaded from '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-06-08T10:58:50.171040+00:00 INFO] [activity:215] Probe: capture-certificate
[2023-06-08T10:58:50.513806+00:00 DEBUG] [python:33] Activity 'capture-certificate' loaded from '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/activities/tls/probes.py'
[2023-06-08T10:58:50.598080+00:00 DEBUG] [activity:235]   => succeeded with '{'conn': {'version': 'TLSv1.3', 'remote_addr': '75.2.60.5:443'}, 'cert': {'fingerprints': {'md5': 'b1cbd5c2a00cbc2114f81dd953428960', 'sha1': '735c302df5052960191618d34f2f58e3487be951', 'sha256': '631a8afbc1efabd321a8e1dca06149fd3ac5a519fe44522c6960295e83d6642f'}, 'extensions': {'subjectAltName': ['reliably.com', 'www.reliably.com']}, 'issuer': "CN=R3,O=Let's Encrypt,C=US", 'subject': 'CN=reliably.com', 'serial': '366996922602068184606233205979119837107355', 'version': 'v3', 'signature_hash': 'sha256', 'not_valid_before': '2023-05-26T08:30:11', 'not_valid_after': '2023-08-24T08:30:10'}}'
[2023-06-08T10:58:50.881581+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'activity'
[2023-06-08T10:58:50.882063+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-06-08T10:58:50.882401+00:00 DEBUG] [__init__:459] Applying after-control 'reliably-integration-slack' on 'activity'
[2023-06-08T10:58:50.882699+00:00 DEBUG] [python:196] Control 'after_activity_control' loaded from '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-06-08T10:58:51.237559+00:00 DEBUG] [hypothesis:226] allowed tolerance is {'name': 'verifiy-tls-certificate', 'type': 'probe', 'provider': {'func': 'verify_tls_cert', 'type': 'python', 'module': 'chaosreliably.activities.tls.tolerances', 'arguments': {'issuer': '${reliably_issuer}', 'alt_names': '${reliably_alt_names}', 'expire_after': '${reliably_expire_after}', 'fingerprint_sha256': '${reliably_fingerprint}'}}}
[2023-06-08T10:58:51.238225+00:00 DEBUG] [python:33] Activity 'verifiy-tls-certificate' loaded from '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/activities/tls/tolerances.py'
[2023-06-08T10:58:51.238493+00:00 DEBUG] [tolerances:29] Cert expires on 2023-08-24T08:30:10
[2023-06-08T10:58:51.238590+00:00 DEBUG] [tolerances:53] Alt names: {'www.reliably.com', 'reliably.com'} / Expected alt names: ['reliably.com', 'www.reliably.com']
[2023-06-08T10:58:51.238663+00:00 INFO] [hypothesis:236] Steady state hypothesis is met!
[2023-06-08T10:58:51.238757+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'hypothesis'
[2023-06-08T10:58:51.238826+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_hypothesis_control'
[2023-06-08T10:58:51.238888+00:00 DEBUG] [__init__:459] Applying after-control 'reliably-integration-slack' on 'hypothesis'
[2023-06-08T10:58:51.238946+00:00 DEBUG] [python:196] Control 'after_hypothesis_control' loaded from '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-06-08T10:58:51.593891+00:00 INFO] [run:663] Playing your experiment's method now...
[2023-06-08T10:58:51.594388+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'method'
[2023-06-08T10:58:51.594707+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_method_control'
[2023-06-08T10:58:51.595053+00:00 INFO] [activity:133] No declared activities, let's move on.
[2023-06-08T10:58:51.595340+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'method'
[2023-06-08T10:58:51.595611+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_method_control'
[2023-06-08T10:58:51.595931+00:00 DEBUG] [run:590] Running steady-state hypothesis after the method
[2023-06-08T10:58:51.596200+00:00 INFO] [hypothesis:186] Steady state hypothesis: Capture certificate and perform the checks
[2023-06-08T10:58:51.596488+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'hypothesis'
[2023-06-08T10:58:51.596777+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_hypothesis_control'
[2023-06-08T10:58:51.597080+00:00 DEBUG] [__init__:459] Applying before-control 'reliably-integration-slack' on 'hypothesis'
[2023-06-08T10:58:51.597354+00:00 DEBUG] [python:196] Control 'before_hypothesis_control' loaded from '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-06-08T10:58:51.757298+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'activity'
[2023-06-08T10:58:51.757740+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_activity_control'
[2023-06-08T10:58:51.758071+00:00 DEBUG] [__init__:459] Applying before-control 'reliably-integration-slack' on 'activity'
[2023-06-08T10:58:51.758357+00:00 DEBUG] [python:196] Control 'before_activity_control' loaded from '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-06-08T10:58:51.873257+00:00 INFO] [activity:215] Probe: capture-certificate
[2023-06-08T10:58:52.214160+00:00 DEBUG] [python:33] Activity 'capture-certificate' loaded from '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/activities/tls/probes.py'
[2023-06-08T10:58:52.288350+00:00 DEBUG] [activity:235]   => succeeded with '{'conn': {'version': 'TLSv1.3', 'remote_addr': '75.2.60.5:443'}, 'cert': {'fingerprints': {'md5': 'b1cbd5c2a00cbc2114f81dd953428960', 'sha1': '735c302df5052960191618d34f2f58e3487be951', 'sha256': '631a8afbc1efabd321a8e1dca06149fd3ac5a519fe44522c6960295e83d6642f'}, 'extensions': {'subjectAltName': ['reliably.com', 'www.reliably.com']}, 'issuer': "CN=R3,O=Let's Encrypt,C=US", 'subject': 'CN=reliably.com', 'serial': '366996922602068184606233205979119837107355', 'version': 'v3', 'signature_hash': 'sha256', 'not_valid_before': '2023-05-26T08:30:11', 'not_valid_after': '2023-08-24T08:30:10'}}'
[2023-06-08T10:58:52.577240+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'activity'
[2023-06-08T10:58:52.577744+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_activity_control'
[2023-06-08T10:58:52.578074+00:00 DEBUG] [__init__:459] Applying after-control 'reliably-integration-slack' on 'activity'
[2023-06-08T10:58:52.578367+00:00 DEBUG] [python:196] Control 'after_activity_control' loaded from '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-06-08T10:58:53.180285+00:00 DEBUG] [hypothesis:226] allowed tolerance is {'name': 'verifiy-tls-certificate', 'type': 'probe', 'provider': {'func': 'verify_tls_cert', 'type': 'python', 'module': 'chaosreliably.activities.tls.tolerances', 'arguments': {'issuer': '${reliably_issuer}', 'alt_names': '${reliably_alt_names}', 'expire_after': '${reliably_expire_after}', 'fingerprint_sha256': '${reliably_fingerprint}', 'value': {'conn': {'version': 'TLSv1.3', 'remote_addr': '75.2.60.5:443'}, 'cert': {'fingerprints': {'md5': 'b1cbd5c2a00cbc2114f81dd953428960', 'sha1': '735c302df5052960191618d34f2f58e3487be951', 'sha256': '631a8afbc1efabd321a8e1dca06149fd3ac5a519fe44522c6960295e83d6642f'}, 'extensions': {'subjectAltName': ['reliably.com', 'www.reliably.com']}, 'issuer': "CN=R3,O=Let's Encrypt,C=US", 'subject': 'CN=reliably.com', 'serial': '366996922602068184606233205979119837107355', 'version': 'v3', 'signature_hash': 'sha256', 'not_valid_before': '2023-05-26T08:30:11', 'not_valid_after': '2023-08-24T08:30:10'}}}}}
[2023-06-08T10:58:53.181182+00:00 DEBUG] [python:33] Activity 'verifiy-tls-certificate' loaded from '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/activities/tls/tolerances.py'
[2023-06-08T10:58:53.181687+00:00 DEBUG] [tolerances:29] Cert expires on 2023-08-24T08:30:10
[2023-06-08T10:58:53.181985+00:00 DEBUG] [tolerances:53] Alt names: {'www.reliably.com', 'reliably.com'} / Expected alt names: ['reliably.com', 'www.reliably.com']
[2023-06-08T10:58:53.182278+00:00 INFO] [hypothesis:236] Steady state hypothesis is met!
[2023-06-08T10:58:53.182561+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'hypothesis'
[2023-06-08T10:58:53.182838+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_hypothesis_control'
[2023-06-08T10:58:53.183095+00:00 DEBUG] [__init__:459] Applying after-control 'reliably-integration-slack' on 'hypothesis'
[2023-06-08T10:58:53.183368+00:00 DEBUG] [python:196] Control 'after_hypothesis_control' loaded from '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-06-08T10:58:53.805089+00:00 WARNING] [run:706] Rollbacks were explicitly requested to be played
[2023-06-08T10:58:53.805255+00:00 INFO] [run:943] Let's rollback...
[2023-06-08T10:58:53.805357+00:00 DEBUG] [__init__:459] Applying before-control 'reliably' on 'rollback'
[2023-06-08T10:58:53.805435+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'before_rollback_control'
[2023-06-08T10:58:53.805493+00:00 INFO] [rollback:31] No declared rollbacks, let's move on.
[2023-06-08T10:58:53.805566+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'rollback'
[2023-06-08T10:58:53.805626+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_rollback_control'
[2023-06-08T10:58:53.805696+00:00 INFO] [run:510] Experiment ended with status: completed
[2023-06-08T10:58:53.805755+00:00 DEBUG] [__init__:459] Applying after-control 'reliably' on 'experiment'
[2023-06-08T10:58:53.805812+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'after_experiment_control'
[2023-06-08T10:58:53.805863+00:00 DEBUG] [__init__:459] Applying after-control 'reliably-integration-slack' on 'experiment'
[2023-06-08T10:58:53.805923+00:00 DEBUG] [python:196] Control 'after_experiment_control' loaded from '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosslack/control.py'
[2023-06-08T10:58:54.175595+00:00 DEBUG] [__init__:103] Cleaning up controls
[2023-06-08T10:58:54.175780+00:00 DEBUG] [__init__:112] Cleaning up control 'reliably'
[2023-06-08T10:58:54.176198+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosreliably/controls/experiment.py' does not declare 'cleanup_control'
[2023-06-08T10:58:54.176537+00:00 DEBUG] [__init__:265] Cleaning up global control 'reliably-integration-slack'
[2023-06-08T10:58:54.176852+00:00 DEBUG] [python:192] Control module '/home/runner/work/acme/acme/.venv/lib/python3.11/site-packages/chaosslack/control.py' does not declare 'cleanup_control'
[2023-06-08T10:58:54.177169+00:00 INFO] [experiment:248] Finishing Reliably execution...
[2023-06-08T10:58:54.606881+00:00 DEBUG] [experiment:163] Stopping Reliably state checker now
[2023-06-08T10:58:54.607298+00:00 DEBUG] [experiment:494] Completing execution '91636fe5-ca1a-4342-ba7d-8b05e2077007' status: completed
[2023-06-08T10:58:54.998888+00:00 DEBUG] [experiment:587] Sending plan '55e8c598-fa50-46d6-aec7-7b8544afc971' status: completed
[2023-06-08T10:58:55.284181+00:00 DEBUG] [experiment:612] Sending execution state: {'current': 'finished', 'status': 'completed', 'deviated': False, 'plan_id': '55e8c598-fa50-46d6-aec7-7b8544afc971'}
[2023-06-08T10:58:55.931019+00:00 INFO] [experiment:311] Finished Reliably execution. Bye!
[2023-06-08T10:58:55.931227+00:00 DEBUG] [caching:42] Clearing activities cache
